config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  resources :books
  resources :book_loans
  resources :book_requests

  root "books#index"
  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/book.rb
class Book < ApplicationRecord

    validates :title, :author, :isbn, :publisher, :published_date, :category, :copy, :status, presence: true
    validates :isbn, uniqueness: true
    validates :copy, numericality: { greater_than: 0,  only_integer: true }
    validates :status, inclusion: {:in => ['AVAILABLE', 'UNAVAILABLE']}
end

app/models/book_loan.rb
class BookLoan < ApplicationRecord
  belongs_to :book

  validates :book, :user, :loan_date, :return_date, presence: true
  validates :status, presence: true, inclusion: {:in => ['RETURNED', 'DUE', 'OVERDUE']}
end

app/models/book_request.rb
class BookRequest < ApplicationRecord

    validates :user, :title, :category, presence: true
    validates :status, presence: true, inclusion: {:in => ['ACCEPTED', 'DENIED', 'PENDING']}
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/book_loans_controller.rb
class BookLoansController < ApplicationController
    before_action :set_book_loan, only: %i[ show edit update destroy ]

    def index
        @book_loans = BookLoan.all
    end

    def new
        @book_loan = BookLoan.new
    end

    def show
    end

    def create
        @book_loan = BookLoan.new(book_loan_params)

        respond_to do |format|
            
            if @book_loan.save
                format.html {redirect_to book_loan_url(@book_loan), notice: "Loan was succesfully created"}
                format.json {render :show, status: :created, location: @book_loan}
            else
                format.html {render :new, status: :unprocessable_entity}
                format.json {render json: @book_loan.errors, status: :unprocessable_entity }
            end
        end
    end

    def update
        respond_to do |format|
            if @book_loan.update(book_loan_params)
                format.html {redirect_to book_loan_url(@book_loan), notice: "Loan was succesfully updated"}
                format.json {render :show, status: :created, location: @book_loan}
            else
                format.html {render :new, status: :unprocessable_entity}
                format.json {render json: @book_loan.errors, status: :unprocessable_entity }
            end
        end
    end

    def destroy
        @book_loan.destroy
        respond_to do |format|
            format.html { redirect_to book_loans_url, notice: "Loan was succesfully deleted" }
            format.json {head :no_content}
        end
    end

    private

    def set_book_loan
        @book_loan = BookLoan.find(params[:id])
    end

    def book_loan_params
        params.require(:book_loan).permit(:book_id, :user, :loan_date, :return_date, :status)
    end
end

app/controllers/book_requests_controller.rb
class BookRequestsController < ApplicationController
    before_action :set_book_request, only: %i[ show edit update destroy ]

    def index
        @book_requests = BookRequest.all
    end

    def show
    end

    def new
        @book_request = BookRequest.new
    end

    def edit
    end

    def create
        @book_request = BookRequest.new(book_request_params)

        respond_to do |format|
            if @book_request.save
                format.html { redirect_to book_request_url(@book_request), notice: "book_request was successfully created." }
                format.json { render :show, status: :created, location: @book_request }
            else
                format.html { render :new, status: :unprocessable_entity }
                format.json { render json: @book_request.errors, status: :unprocessable_entity }
            end
        end
    end

    def update
        respond_to do |format|
            if @book_request.update(book_request_params)
                format.html { redirect_to book_request_url(@book_request), notice: "book_request was successfully updated." }
                format.json { render :show, status: :ok, location: @book_request }
            else
                format.html { render :edit, status: :unprocessable_entity }
                format.json { render json: @book_request.errors, status: :unprocessable_entity }
            end
        end
    end

    def destroy
        @book_request.destroy
        respond_to do |format|
            format.html { redirect_to book_requests_url, notice: "book_request was successfully destroyed." }
            format.json { head :no_content }
        end
    end

    private

    def set_book_request
        @book_request = BookRequest.find(params[:id])
    end

    def book_request_params
        params.require(:book_request).permit(:user, :isbn, :title, :publisher, :published_date, :category, :status)
    end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
    before_action :set_book, only: %i[ show edit update destroy ]

    def index
        @books = Book.all
    end

    def show
    end

    def new
        @book = Book.new
    end

    def edit
    end

    def create
        @book = Book.new(book_params)

        respond_to do |format|
            if @book.save
                format.html { redirect_to book_url(@book), notice: "Book was successfully created." }
                format.json { render :show, status: :created, location: @book }
            else
                format.html { render :new, status: :unprocessable_entity }
                format.json { render json: @book.errors, status: :unprocessable_entity }
            end
        end
    end

    def update
        respond_to do |format|
            if @book.update(book_params)
                format.html { redirect_to book_url(@book), notice: "Book was successfully updated." }
                format.json { render :show, status: :ok, location: @book }
            else
                format.html { render :edit, status: :unprocessable_entity }
                format.json { render json: @book.errors, status: :unprocessable_entity }
            end
        end
    end

    def destroy
        @book.destroy
        respond_to do |format|
            format.html { redirect_to books_url, notice: "book was successfully destroyed." }
            format.json { head :no_content }
        end
    end

    private

    def set_book
        @book = Book.find(params[:id])
    end

    def book_params
        params.require(:book).permit(:title, :author, :isbn, :publisher, :published_date, :category, :description, :copy, :status)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/book_loans_helper.rb
module BookLoansHelper
end

app/helpers/book_requests_helper.rb
module BookRequestsHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/views/book_loans/_book_loan.html.erb
<div id="<%= dom_id book_loan %>">
    <h1><%= book_loan.book.title %></h1>
    <p>
        <strong>User:</strong>
        <%= book_loan.user %>
    </p>

     <p>
        <strong>Loan Date:</strong>
        <%= book_loan.loan_date %>
    </p>

     <p>
        <strong>Return Date:</strong>
        <%= book_loan.return_date %>
    </p>

     <p>
        <strong>Status:</strong>
        <%= book_loan.status %>
    </p>


</div>

app/views/book_loans/_form.html.erb
<div class="container">
    <div class="row">
        <div class="col-sm-4">
        <%= form_with(model: book_loan) do |form| %>
            <% if book_loan.errors.any? %>
            <div style="color: red">
                <h2><%= pluralize(book_loan.errors.count, "error") %> prohibited this book_loan from being saved:</h2>

                <ul>
                <% book_loan.errors.each do |error| %>
                    <li><%= error.full_message %></li>
                <% end %>
                </ul>
            </div>
            <% end %>

            <div>
            <%= form.label :book, style: "display: block" %>
            <%= form.collection_select :book_id, Book.order(:id),:id, :title ,class: "form-control" %>
            </div>

            <div>
            <%= form.label :user, style: "display: block" %>
            <%= form.text_field :user, class: "form-control" %>
            </div>

            <div>
            <%= form.label :loan_date, style: "display: block" %>
            <%= form.text_field :loan_date, class: "form-control" %>
            </div>

            <div>
            <%= form.label :return_date, style: "display: block" %>
            <%= form.text_field :return_date, class: "form-control" %>
            </div>

            <div>
            <%= form.label :status, style: "display: block" %>
            <%= form.text_field :status, class: "form-control" %>
            </div>
            
            
            <br>
            <div>
            <%= form.submit class: "btn btn-primary" %>
            </div>
        <% end %>
        </div>
    </div>
</div>

app/views/book_loans/edit.html.erb
<h1>Editing book_loan</h1>

<%= render "form", book_loan: @book_loan %>

<br>

<div>
    <%= link_to "Show this book_loan", @book_loan , class: "btn btn-primary"%>
    <%= link_to "Back to book_loans", book_loans_path, class: "btn btn-primary" %>
</div>

app/views/book_loans/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>book_loans</h1>

<%= link_to "New book_loan", new_book_loan_path,class: "btn btn-primary" %>
<br>
<br>
<br>
<table class="table table-striped table-hover">
    <thead>
        <tr>
            <th>Book</th>
            <th>ISBN</th>
            <th>User</th>
            <th>Loan Date</th>
            <th>Return Date</th>
            <th>Status</th>
            <th>OPTIONS</th>
        </tr>
    </thead>
    <tbody>
        <% @book_loans.each do |book_loan| %>
        <tr>
            <td><%= book_loan.book.title %></td>
            <td><%= book_loan.book.isbn %></td>
            <td><%= book_loan.user %></td>
            <td><%= book_loan.loan_date %></td>
            <td><%= book_loan.return_date %></td>
            <td><%= book_loan.status %></td>
            <td>
            <%= link_to "Show", book_loan, class: "btn btn-small" %>
            &nbsp;
            <%= link_to "Edit", edit_book_loan_path(book_loan), class: "btn btn-small" %>
            </td>
        </tr>
        <% end %>
    </tbody>
    </table>

app/views/book_loans/new.html.erb
<h1>New book_loan</h1>

<%= render "form", book_loan: @book_loan %>

<br>

<div>
    <%= link_to "Back to book_loans", book_loans_path, class: "btn btn-primary" %>
</div>

app/views/book_loans/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @book_loan %>

<div>
    <%= link_to "Edit this book_loan", edit_book_loan_path(@book_loan), class: "btn btn-primary"%> 
    <%= link_to "Back to book_loans", book_loans_path, class: "btn btn-primary" %>
    <br>
    <br>
    <%= button_to "Destroy this book_loan", @book_loan, method: :delete  , class: "btn btn-primary"%>
</div>

app/views/book_requests/_book_request.html.erb
<div id="<%= dom_id book_request %>">
        <h1><%= book_request.user %></h1>
        <p>
            <strong>Title:</strong>
            <%= book_request.user %>
        </p>

        <p>
            <strong>Title:</strong>
            <%= book_request.isbn %>
        </p>

        <p>
            <strong>Title:</strong>
            <%= book_request.title %>
        </p>

        <p>
            <strong>Title:</strong>
            <%= book_request.publisher %>
        </p>

        <p>
            <strong>Title:</strong>
            <%= book_request.published_date %>
        </p>

        <p>
            <strong>Title:</strong>
            <%= book_request.category %>
        </p>

        <p>
            <strong>Title:</strong>
            <%= book_request.status %>
        </p>


</div>

app/views/book_requests/_form.html.erb
<div class="container">
    <div class="row">
        <div class="col-sm-4">
        <%= form_with(model: book_request) do |form| %>
            <% if book_request.errors.any? %>
            <div style="color: red">
                <h2><%= pluralize(book_request.errors.count, "error") %> prohibited this book_request from being saved:</h2>

                <ul>
                <% book_request.errors.each do |error| %>
                    <li><%= error.full_message %></li>
                <% end %>
                </ul>
            </div>
            <% end %>

            <div>
            <%= form.label :user, style: "display: block" %>
            <%= form.text_field :user, class: "form-control" %>
            </div>

            <div>
            <%= form.label :isbn, style: "display: block" %>
            <%= form.text_field :isbn, class: "form-control" %>
            </div>

            <div>
            <%= form.label :title, style: "display: block" %>
            <%= form.text_field :title, class: "form-control" %>
            </div>

            <div>
            <%= form.label :publisher, style: "display: block" %>
            <%= form.text_field :publisher, class: "form-control" %>
            </div>

            <div>
            <%= form.label :published_date, style: "display: block" %>
            <%= form.text_field :published_date, class: "form-control" %>
            </div>

            <div>
            <%= form.label :category, style: "display: block" %>
            <%= form.text_field :category, class: "form-control" %>
            </div>

            <div>
            <%= form.label :status, style: "display: block" %>
            <%= form.text_field :status, class: "form-control" %>
            </div>
            
            
            <br>
            <div>
            <%= form.submit class: "btn btn-primary" %>
            </div>
        <% end %>
        </div>
    </div>
</div>

app/views/book_requests/edit.html.erb
<h1>Editing book_request</h1>

<%= render "form", book_request: @book_request %>

<br>

<div>
    <%= link_to "Show this book_request", @book_request , class: "btn btn-primary"%>
    <%= link_to "Back to book_requests", book_requests_path, class: "btn btn-primary" %>
</div>

app/views/book_requests/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>book_requests</h1>

<%= link_to "New book_request", new_book_request_path,class: "btn btn-primary" %>
<br>
<br>
<br>
<table class="table table-striped">
    <thead>
        <tr>
            <th>User</th>
            <th>ISBN</th>
            <th>Title</th>
            <th>Publisher</th>
            <th>published_date</th>
            <th>Category</th>
            <th>Status</th>
            <th>OPTIONS</th>
        </tr>
    </thead>
    <tbody>
        <% @book_requests.each do |book_request| %>
        <tr>
            <td><%= book_request.user %></td>
            <td><%= book_request.isbn %></td>
            <td><%= book_request.title %></td>
            <td><%= book_request.publisher %></td>
            <td><%= book_request.published_date %></td>
            <td><%= book_request.category %></td>
            <td><%= book_request.status %></td>
            <td>
            <%= link_to "Show", book_request, class: "btn btn-primary" %>
            &nbsp;
            <%= link_to "Edit", edit_book_request_path(book_request), class: "btn btn-primary" %>
            </td>
        </tr>
        <% end %>
    </tbody>
    </table>

app/views/book_requests/new.html.erb
<h1>New book_request</h1>

<%= render "form", book_request: @book_request %>

<br>

<div>
    <%= link_to "Back to book_requests", book_requests_path, class: "btn btn-primary" %>
</div>

app/views/book_requests/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @book_request %>

<div>
    <%= link_to "Edit this book_request", edit_book_request_path(@book_request), class: "btn btn-primary"%> 
    <%= link_to "Back to book_requests", book_requests_path, class: "btn btn-primary" %>
    <br>
    <br>
    <%= button_to "Destroy this book_request", @book_request, method: :delete  , class: "btn btn-primary"%>
</div>

app/views/books/_book.html.erb
<div id="<%= dom_id book %>">
    <h1><%= book.title %></h1>
    <p>
        <strong>Title:</strong>
        <%= book.title %>
    </p>

    <p>
        <strong>Author:</strong>
        <%= book.author %>
    </p>

    <p>
        <strong>ISBN:</strong>
        <%= book.isbn %>
    </p>

    <p>
        <strong>Publisher:</strong>
        <%= book.publisher %>
    </p>

    <p>
        <strong>published_date:</strong>
        <%= book.published_date %>
    </p>

    <p>
        <strong>Category:</strong>
        <%= book.category %>
    </p>

    <p>
        <strong>Description:</strong>
        <%= book.description %>
    </p>

    <p>
        <strong>Copy:</strong>
        <%= book.copy %>
    </p>

    <p>
        <strong>Status:</strong>
        <%= book.status %>
    </p>

</div>

app/views/books/_form.html.erb
<div class="container">
    <div class="row">
        <div class="col-sm-4">
        <%= form_with(model: book) do |form| %>
            <% if book.errors.any? %>
            <div style="color: red">
                <h2><%= pluralize(book.errors.count, "error") %> prohibited this book from being saved:</h2>

                <ul>
                <% book.errors.each do |error| %>
                    <li><%= error.full_message %></li>
                <% end %>
                </ul>
            </div>
            <% end %>

            <div>
            <%= form.label :title, style: "display: block" %>
            <%= form.text_field :title, class: "form-control" %>
            </div>

            <div>
            <%= form.label :author, style: "display: block" %>
            <%= form.text_field :author, class: "form-control" %>
            </div>

            <div>
            <%= form.label :isbn, style: "display: block" %>
            <%= form.text_field :isbn, class: "form-control" %>
            </div>

            <div>
            <%= form.label :publisher, style: "display: block" %>
            <%= form.text_field :publisher, class: "form-control" %>
            </div>

            <div>
            <%= form.label :published_date, style: "display: block" %>
            <%= form.text_field :published_date, class: "form-control" %>
            </div>
            
            <div>
            <%= form.label :category, style: "display: block" %>
            <%= form.text_field :category, class: "form-control" %>
            </div>

            <div>
            <%= form.label :description, style: "display: block" %>
            <%= form.text_area :description, class: "form-control" %>
            </div>

            <div>
            <%= form.label :copy, style: "display: block" %>
            <%= form.number_field :copy, class: "form-control" %>
            </div>

            <div>
            <%= form.label :status, style: "display: block" %>
            <%= form.text_field :status, class: "form-control" %>
            </div>
            <br>
            <div>
            <%= form.submit class: "btn btn-primary" %>
            </div>
        <% end %>
        </div>
    </div>
</div>

app/views/books/edit.html.erb
<h1>Editing book</h1>

<%= render "form", book: @book %>

<br>

<div>
    <%= link_to "Show this book", @book , class: "btn btn-primary"%>
    <%= link_to "Back to books", books_path, class: "btn btn-primary" %>
</div>

app/views/books/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Books</h1>

<%= link_to "New book", new_book_path,class: "btn btn-primary" %>
<br>
<br>
<br>
<table class="table table-striped">
    <thead>
        <tr>
            <th>Title</th>
            <th>Author</th>
            <th>ISBN</th>
            <th>Publisher</th>
            <th>Published Date</th>
            <th>Category</th>
            <th>Description</th>
            <th>Copy</th>
            <th>Status</th>
            <th>OPTIONS</th>
        </tr>
    </thead>
    <tbody>
        <% @books.each do |book| %>
        <tr>
            <td><%= book.title %></td>
            <td><%= book.author %></td>
            <td><%= book.isbn %></td>
            <td><%= book.publisher %></td>
            <td><%= book.published_date %></td>
            <td><%= book.category %></td>
            <td><%= book.description %></td>
            <td><%= book.copy %></td>
            <td><%= book.status %></td>
            <td>
            <%= link_to "Show", book, class: "btn btn-primary" %>
            &nbsp;
            <%= link_to "Edit", edit_book_path(book), class: "btn btn-primary" %>
            </td>
        </tr>
        <% end %>
    </tbody>
    </table>

app/views/books/new.html.erb
<h1>New book</h1>

<%= render "form", book: @book %>

<br>

<div>
    <%= link_to "Back to books", books_path, class: "btn btn-primary" %>
</div>

app/views/books/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @book %>

<div>
    <%= link_to "Edit this book", edit_book_path(@book), class: "btn btn-primary"%> 
    <%= link_to "Back to books", books_path, class: "btn btn-primary" %>
    <br>
    <br>
    <%= button_to "Destroy this book", @book, method: :delete  , class: "btn btn-primary"%>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Lms</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-0evHe/X+R7YkIZDRvuzKMRqM+OrBnVFBL6DOitfPri4tjfHxaWutUpFmBp4vmVor" crossorigin="anonymous">
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
  <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <div class="container-fluid">
    <%= link_to 'LMS', root_path, class:"navbar-brand" %>
    <br>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        
        <li class="nav-item">
          <%= link_to "BOOKS", books_path , class:"nav-link"%>
        </li>

        <li class="nav-item">
          <%= link_to "BOOK REQUEST", book_requests_path , class:"nav-link"%>
        </li>

        <li class="nav-item">
          <%= link_to "BOOK LOAN", book_loans_path , class:"nav-link"%>
        </li>

      </ul>
    </div>
  </div>
</nav>
    <%= yield %>
  </body>
</html>